# meta
title: ML Blog
author: Marko Lalovic
last_modified: "2024-05-17"
about: "https://lalovic.io"
email: marko@lalovic.me
description: "A technical blog on optimization, machine learning, statistics and areas of applied mathematics."
baseurl: "/blog"
url: "https://lalovic.io"
repository: markolalovic/blog
github_username: markolalovic

# blogposts
collections:
  my_posts:
    permalink: "/:path/"
    output: true

# JTD theme settings
theme: just-the-docs

just_the_docs:
  collections:
    my_posts:
      name: Posts

favicon_ico: "/assets/icons/favicon.ico"

heading_anchors: false

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple

# supress jekyll build warnings
sass:
  quiet_deps: true

# jekyll-scholar plugin settings
scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending
  source: ./_bibliography
  bibliography: simple.bib
  bibliography_template: ""
  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"
  bibtex_filters:
    - HtmlLinks
    - DOILinks  

# comments via contact forms
comments:
  use: "staticforms"
  staticforms:
    action: "https://api.staticforms.xyz/submit"
    token: "4e5a5ee1-5fd9-47ed-9b85-aecdabd0c006"
  web3forms:
    action: "https://api.web3forms.com/submit"
    token: "20a51aef-da18-46db-a079-fd60a0b9c065"