# Site settings
title: Marko Lalovic
email: marko.lalovic@yahoo.com
description: >-
  Technical blog on machine learning, programming and and other math-related topics.
baseurl: "/blog/"
icon: "📖"
url: "https://markolalovic.me"
twitter_username: MarkoLalovic
github_username:  markolalovic

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Output settings
permalink: /:title

# Comments
staticman_url: https://markos-staticman.herokuapp.com/v2/entry/markolalovic/blog/main/comments
comments: true
reCaptcha:
  siteKey: "6Ld9SSAcAAAAAIOAnnTxS877afNki9ImVkuOPCKf"
  secret: "s8VT5a9nr8XJEDMua1npoAfWZJ/gUHXXrwwRbtVTHL/wTtvRsKuEc24mA5RVT61TSsldsgna/gXCc/epqQLr7oLvRFRMn45WLTsE121uBc4fDmED7PNzRfNkWw7//1uZQ3cpdr1rNM9gGcdHzgEJoolkkGmYDG4wNDKBurjFJ7sLXxhqeZtaJt8kqrrBQEKUXnBZwTriDTPpda0iCmZpc4509WdGtCpGR082wQGxNSGTX+zbj5PMO88mrjumXGYx7OH9R31dz2nVjmHjfYgEgOlNFBpdO1wKMB7IzC/qtxc9W9OVd6bpBHEiRYJdCf+idnot/zdVtqMHCJvf1RwlxdU/JxBnElc9l6fmCrSl1bJladliu7xUIqCyeEzz+1CCHhgnHpUSY5+VhTKx62W04qKoMh+JoN5ZHozH8kthkTNnpVqSXB8jjyP4kZEccrSfQ17sa4qlM2++MrYDolFhA9Fp1flxOBBzjCR8vhiuIXtI2iPXdxnvIIJfwuyX3AxJfdK1lwRtCaZKRy6IT3FEzqRc521SVsGqUByATEOmXYSxDCx+bonyyDd8QE4TNPSIyY+/y0Vg0o1BUeoIu6oaUjeOmp6RpPU116xwXwkpqG8PV21+oFkVkOBUDR/hAmd/b7y1F4ZN2puGrtEiVMI8kRjBMa0wy4JxyQyOb95p69U="
