# Site settings
title: Marko Lalović
email: marko@markolalovic.com
description: >-
  A blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # https://markolalovic.com
twitter_username: MarkoLalovic
github_username:  markolalovic

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Output settings
# permalink
permalink: /:title

# Comments
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
# https://markos-staticman.herokuapp.com/v2/connect/markolalovic/blog
staticman_url: https://markos-staticman.herokuapp.com/v2/entry/markolalovic/blog/main/comments

reCaptcha:
  siteKey: 6Ld9SSAcAAAAAIOAnnTxS877afNki9ImVkuOPCKf
  secret: h7X0G5bI7uqElE+sqtffVTnBpwl3HOdBxEMNkCeYX2GZfHjgenf8Rg7XPM7IKIArDhbq5vmJ67zjVf8qtT2A4dp4WsE9eYKgDCaycDMeS2OeHCqXcuLx25wkPdhurm+YTdCwquo4ogqXF8M08ySwaZCUjAY+3MF9J0QrAoHAFjjT1Gd7bH5hTmAljMoajQX0J/tXbhTj6TR0Ctw2l9GY6mBCYkx1n2JzVVBCLPouCsGlLWAfmwoQhviuUAaaP0L+UG2Gbiuj50iAyTLPhxXbnxS58ot7Y74KGpusf9dDZqPkU7t5h4VnFSuoV1pOKE4qBhi1AVTGTHyCGWzw3BJoCw==
