# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ML Blog
author: Marko Lalovic
last_modified: "2024-05-17"
about: "https://lalovic.io"
email: marko@lalovic.me
description: "A technical blog."
baseurl: "/blog"
url: "https://lalovic.io"

repository: markolalovic/blog # for github-metadata
github_username: markolalovic

collections:
  my_posts:
    permalink: "/:path/"
    output: true

# JTD settings
theme: just-the-docs

just_the_docs:
  collections:
    my_posts:
      name: Posts

favicon_ico: "/assets/icons/favicon.ico"

heading_anchors: false

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple

# supress jekyll build warnings
sass:
  quiet_deps: true

# jekyll-scholar plugin settings
scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending
  source: ./_bibliography
  bibliography: simple.bib
  bibliography_template: ""
  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"
  bibtex_filters:
    - HtmlLinks
    - DOILinks  

# comments via contact forms
comments:
  use: "staticforms"
  staticforms:
    action: "https://api.staticforms.xyz/submit"
    token: "4e5a5ee1-5fd9-47ed-9b85-aecdabd0c006"
  web3forms:
    action: "https://api.web3forms.com/submit"
    token: "20a51aef-da18-46db-a079-fd60a0b9c065"